import type { AnimeScene, LyricLine } from "./types";

export const FPS = 30;
export const MUSIC_FILE = "anime-clip/audio/Young Girl A (Tradução + Letra_Legenda) - Gabii (youtube).mp3";
export const VIDEO_DURATION_SECONDS = 240;

// Character bible: paste this unchanged at the beginning of every AI prompt.
export const CHARACTER_BIBLE = `Recurring protagonist: Ren, 19-year-old Japanese man, slender athletic build, oval face, expressive amber-gold eyes, short tousled black hair with one silver fringe over the right eyebrow, small crescent scar beneath left eye, charcoal high-collar jacket with a thin cobalt-blue lining, black shirt, dark fitted trousers, weathered brown wristband on left wrist. Keep the exact same face, eyes, hair, age, body and outfit in every scene.`;
export const NEGATIVE_PROMPT = "text, letters, subtitles, watermark, logo, low resolution, blurry, deformed face, bad anatomy, malformed hands, extra fingers, misaligned eyes, different character, changed hair, inconsistent clothes, wrong proportions, cluttered composition, 3D render, photorealistic, generic art";

const scenes: Omit<AnimeScene, "start">[] = [
  { id:"01", title:"INTRO — THE LAST TRAIN", duration:20, lyricNote:"[Replace with opening/instrumental lyric]", visual:"A rain-washed coastal city at blue hour. Ren stands alone on an elevated train platform, holding a small pendant as a distant train light approaches.", prompt:"wide establishing shot of a rain-washed coastal Japanese city at blue hour, Ren on an elevated platform holding a small pendant, distant train headlights, mist, drifting rain, wind lifting his silver fringe, cinematic modern Japanese anime film, detailed architecture, cold cyan and violet light, 16:9", shot:"Plano aberto, câmera alta", camera:"Lento push-in de 8%", emotion:"Mistério e saudade", transition:"Dissolve through train light", asset:"anime-clip/scene-01/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"02", title:"VERSE I — THE PROMISE", duration:20, lyricNote:"[Replace with verse 1 line]", visual:"Ren remembers offering the pendant to a girl beneath a summer festival lantern arch; only her silhouette is shown, preserving a future reveal.", prompt:"medium two-shot, Ren offering a small silver pendant to a young woman seen in soft silhouette beneath summer festival lanterns, warm paper lantern glow against night sky, intimate emotional anime film frame, floating dust and wind, 16:9", shot:"Plano médio lateral", camera:"Travelling suave da esquerda", emotion:"Ternura e promessa", transition:"Match cut: pendant in hand", asset:"anime-clip/scene-02/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"03", title:"VERSE I — EMPTY STREETS", duration:20, lyricNote:"[Replace with verse 1 continuation]", visual:"Back in the present, Ren walks through an empty neon street, his reflection split by puddles, searching for a familiar light.", prompt:"rear tracking shot of Ren walking alone through an empty neon Tokyo side street after rain, fragmented reflection in puddles, cobalt and magenta signs, jacket moving in wind, melancholic modern anime cinematography, shallow depth of field, 16:9", shot:"Perspectiva por trás", camera:"Câmera acompanha Ren", emotion:"Solidão e busca", transition:"Rain wipe", asset:"anime-clip/scene-03/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"04", title:"PRE-CHORUS — THE SIGNAL", duration:20, lyricNote:"[Replace with pre-chorus]", visual:"The pendant begins to glow; wind and rain intensify around Ren as he raises his eyes toward the sea.", prompt:"emotional close-up of Ren's amber-gold eyes and left hand clutching a glowing silver pendant, rain suspended in the air, hair and cobalt-lined jacket swept by violent wind, strong contrast, luminous blue reflections, dramatic anime film, 16:9", shot:"Close-up / extreme close-up", camera:"Dolly-in acelerando", emotion:"Tensão e despertar", transition:"Flash of cobalt light", asset:"anime-clip/scene-04/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"05", title:"CHORUS — RUN TO THE HORIZON", duration:20, lyricNote:"[Replace with chorus]", visual:"Ren runs across a flooded railway bridge toward a glowing horizon; light breaks through storm clouds like a path.", prompt:"epic low-angle wide shot of Ren running across a flooded railway bridge toward a radiant ocean horizon, storm clouds opening with gold and cobalt rays, spray, flying coat, enormous scale, triumphant modern Japanese anime movie, dramatic cinematic lighting, 16:9", shot:"Plano aberto, câmera baixa", camera:"Travelling frontal rápido", emotion:"Determinação e libertação", transition:"White bloom", asset:"anime-clip/scene-05/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"06", title:"VERSE II — WHAT REMAINS", duration:20, lyricNote:"[Replace with verse 2]", visual:"At an abandoned seaside observatory, Ren finds a wall of faded photographs and one missing space where a memory should be.", prompt:"medium shot in an abandoned seaside observatory, Ren studying a wall of faded photographs with one empty torn space, moonlight through cracked glass, dust motes, textured melancholy, cinematic modern anime film, 16:9", shot:"Plano médio com cenário", camera:"Pan lento para o vazio", emotion:"Perda e revelação", transition:"Focus pull into photo", asset:"anime-clip/scene-06/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"07", title:"PRE-CHORUS II — CHOOSE", duration:20, lyricNote:"[Replace with pre-chorus 2]", visual:"Ren's hand hovers over the pendant. In its reflection, the girl reaches from a different time across the glass.", prompt:"symbolic extreme close-up of Ren's hand and glowing pendant reflected in cracked observatory glass, a young woman's hand reaching from the reflected world, rain trails, amber and blue light, intense anime cinematic detail, 16:9", shot:"Detalhe de mãos e olhos", camera:"Rack focus entre reflexo e Ren", emotion:"Conflito e esperança", transition:"Glass shimmer", asset:"anime-clip/scene-07/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"08", title:"CHORUS II — THE WORLD OPENS", duration:20, lyricNote:"[Replace with second chorus]", visual:"The observatory transforms into a field of luminous blue flowers above the city; Ren and the girl stand apart, connected by a stream of light.", prompt:"grand wide aerial shot, ruined seaside observatory transformed into a field of luminous cobalt flowers above a sleeping city, Ren and the same young woman standing apart connected by a ribbon of light, wind, starry sky, breathtaking modern Japanese anime movie, 16:9", shot:"Plano aberto aéreo", camera:"Orbit lento e ascendente", emotion:"Reencontro e expansão", transition:"Petals fill frame", asset:"anime-clip/scene-08/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"09", title:"BRIDGE — LETTING GO", duration:20, lyricNote:"[Replace with bridge]", visual:"At sunrise, the girl fades gently into drifting petals while Ren smiles through tears, accepting the goodbye.", prompt:"contemplative close medium shot at sunrise, Ren smiling through tears as the same young woman softly dissolves into glowing flower petals, warm peach sky, gentle wind, rain ending, deeply emotional anime film, cinematic shallow depth of field, 16:9", shot:"Plano médio íntimo", camera:"Quase estática, slow drift", emotion:"Aceitação e amor", transition:"Fade through petals", asset:"anime-clip/scene-09/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"10", title:"CLIMAX — LIGHT BEYOND THE STORM", duration:20, lyricNote:"[Replace with climax lyric]", visual:"Ren releases the pendant over the ocean; it becomes a vast column of dawn light that clears the storm and restores color to the city.", prompt:"ultimate epic anime movie composition, low angle of Ren at a cliff above the ocean releasing a silver pendant into a colossal column of dawn light, storm breaking apart, city below awakening in color, hair and jacket in fierce wind, emotional extreme expression, particles and cinematic rays, 16:9", shot:"Plano aberto épico, câmera baixa", camera:"Crane up grandioso", emotion:"Transformação e catarse", transition:"Golden flare", asset:"anime-clip/scene-10/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"11", title:"FINAL CHORUS — WALK FORWARD", duration:20, lyricNote:"[Replace with final chorus]", visual:"Ren crosses the now-sunlit bridge with quiet confidence. The pendant's blue lining remains as a memory, but his gaze is forward.", prompt:"cinematic wide shot of Ren walking confidently across the same railway bridge in clear golden morning, calm ocean, subtle cobalt light along his jacket, city alive in distance, wind and birds, resolved modern Japanese anime film, 16:9", shot:"Plano aberto lateral", camera:"Travelling paralelo sereno", emotion:"Vitória serena", transition:"Slow dissolve", asset:"anime-clip/scene-11/visual.jpg", assetKind:"image", hasVisualAsset:false },
  { id:"12", title:"OUTRO — THE HORIZON", duration:20, lyricNote:"[Replace with outro/instrumental lyric]", visual:"Ren becomes a small figure on a sunlit cliff as the camera pulls far back over the endless ocean; fade to black.", prompt:"final ultra wide anime film shot, Ren a small solitary figure on a sunlit coastal cliff facing an endless sparkling ocean, moving grass and birds, peaceful clouds, beautiful cinematic conclusion, clean lower-screen negative space for subtitles, 16:9", shot:"Plano aberto extremo", camera:"Pull-back lento até fade", emotion:"Conclusão e paz", transition:"Fade para preto", asset:"anime-clip/scene-12/visual.jpg", assetKind:"image", hasVisualAsset:false },
];

export const SCENES: AnimeScene[] = scenes.reduce<AnimeScene[]>((all, scene) => {
  const start = all.reduce((sum, item) => sum + item.duration, 0);
  all.push({ ...scene, start }); return all;
}, []);

// Replace these placeholders with licensed lyric lines and their precise start/end timestamps.
export const LYRICS: LyricLine[] = [
  { start: 0, end: 20, original: "[ORIGINAL LYRIC — INTRO]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 20, end: 40, original: "[ORIGINAL LYRIC — VERSO 1]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 40, end: 60, original: "[ORIGINAL LYRIC — VERSO 1]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 60, end: 80, original: "[ORIGINAL LYRIC — PRÉ-REFRÃO]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 80, end: 100, original: "[ORIGINAL LYRIC — REFRÃO]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 100, end: 120, original: "[ORIGINAL LYRIC — VERSO 2]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 120, end: 140, original: "[ORIGINAL LYRIC — PRÉ-REFRÃO]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 140, end: 160, original: "[ORIGINAL LYRIC — REFRÃO]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 160, end: 180, original: "[ORIGINAL LYRIC — PONTE]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 180, end: 200, original: "[ORIGINAL LYRIC — CLÍMAX]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 200, end: 220, original: "[ORIGINAL LYRIC — REFRÃO FINAL]", portuguese: "[TRADUÇÃO EM PORTUGUÊS]" },
  { start: 220, end: 240, original: "[INSTRUMENTAL / OUTRO]", portuguese: "" },
];
